# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/MarkYUV
pkgincludedir = $(includedir)/MarkYUV
pkglibdir = $(libdir)/MarkYUV
pkglibexecdir = $(libexecdir)/MarkYUV
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = yuvaddetect$(EXEEXT) yuvadjust$(EXEEXT) \
	yuvaifps$(EXEEXT) yuvconvolve$(EXEEXT) yuvcrop$(EXEEXT) \
	yuvdeinterlace$(EXEEXT) yuvdiff$(EXEEXT) yuvfade$(EXEEXT) \
	yuvhsync$(EXEEXT) yuvrfps$(EXEEXT) yuvtshot$(EXEEXT) \
	yuvwater$(EXEEXT) yuvbilateral$(EXEEXT) yuvtbilateral$(EXEEXT) \
	yuvpixelgraph$(EXEEXT) $(am__EXEEXT_1) $(am__EXEEXT_2) \
	$(am__EXEEXT_3) $(am__EXEEXT_4)
am__append_1 = libav-bitrate libav2yuv libavmux 
am__append_2 = yuvdiag yuvsubtitle
am__append_3 = yuvCIFilter 
am__append_4 = yuvilace
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__EXEEXT_1 = libav-bitrate$(EXEEXT) \
	libav2yuv$(EXEEXT) libavmux$(EXEEXT)
am__EXEEXT_2 = yuvdiag$(EXEEXT) \
	yuvsubtitle$(EXEEXT)
am__EXEEXT_3 = yuvCIFilter$(EXEEXT)
am__EXEEXT_4 = yuvilace$(EXEEXT)
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__libav_bitrate_SOURCES_DIST = libav-bitrate.c
am_libav_bitrate_OBJECTS = libav-bitrate.$(OBJEXT)
libav_bitrate_OBJECTS = $(am_libav_bitrate_OBJECTS)
libav_bitrate_LDADD = $(LDADD)
am__libav2yuv_SOURCES_DIST = libav2yuv.c
am_libav2yuv_OBJECTS = libav2yuv.$(OBJEXT)
libav2yuv_OBJECTS = $(am_libav2yuv_OBJECTS)
libav2yuv_LDADD = $(LDADD)
am__libavmux_SOURCES_DIST = libavmux.c
am_libavmux_OBJECTS = libavmux.$(OBJEXT)
libavmux_OBJECTS = $(am_libavmux_OBJECTS)
libavmux_LDADD = $(LDADD)
am__yuvCIFilter_SOURCES_DIST = yuvCIFilter.m
am_yuvCIFilter_OBJECTS = yuvCIFilter.$(OBJEXT)
yuvCIFilter_OBJECTS = $(am_yuvCIFilter_OBJECTS)
yuvCIFilter_LDADD = $(LDADD)
am_yuvaddetect_OBJECTS = yuvaddetect.$(OBJEXT)
yuvaddetect_OBJECTS = $(am_yuvaddetect_OBJECTS)
yuvaddetect_LDADD = $(LDADD)
am_yuvadjust_OBJECTS = yuvadjust.$(OBJEXT)
yuvadjust_OBJECTS = $(am_yuvadjust_OBJECTS)
yuvadjust_LDADD = $(LDADD)
am_yuvaifps_OBJECTS = yuvaifps.$(OBJEXT)
yuvaifps_OBJECTS = $(am_yuvaifps_OBJECTS)
yuvaifps_LDADD = $(LDADD)
am_yuvbilateral_OBJECTS = yuvbilateral.$(OBJEXT) utilyuv.$(OBJEXT)
yuvbilateral_OBJECTS = $(am_yuvbilateral_OBJECTS)
yuvbilateral_LDADD = $(LDADD)
am_yuvconvolve_OBJECTS = yuvconvolve.$(OBJEXT)
yuvconvolve_OBJECTS = $(am_yuvconvolve_OBJECTS)
yuvconvolve_LDADD = $(LDADD)
am_yuvcrop_OBJECTS = yuvcrop.$(OBJEXT)
yuvcrop_OBJECTS = $(am_yuvcrop_OBJECTS)
yuvcrop_LDADD = $(LDADD)
am_yuvdeinterlace_OBJECTS = yuvdeinterlace.$(OBJEXT) utilyuv.$(OBJEXT)
yuvdeinterlace_OBJECTS = $(am_yuvdeinterlace_OBJECTS)
yuvdeinterlace_LDADD = $(LDADD)
am__yuvdiag_SOURCES_DIST = yuvdiag.c
am_yuvdiag_OBJECTS = yuvdiag.$(OBJEXT)
yuvdiag_OBJECTS = $(am_yuvdiag_OBJECTS)
yuvdiag_LDADD = $(LDADD)
am_yuvdiff_OBJECTS = yuvdiff.$(OBJEXT) utilyuv.$(OBJEXT)
yuvdiff_OBJECTS = $(am_yuvdiff_OBJECTS)
yuvdiff_LDADD = $(LDADD)
am_yuvfade_OBJECTS = yuvfade.$(OBJEXT)
yuvfade_OBJECTS = $(am_yuvfade_OBJECTS)
yuvfade_LDADD = $(LDADD)
am_yuvhsync_OBJECTS = yuvhsync.$(OBJEXT)
yuvhsync_OBJECTS = $(am_yuvhsync_OBJECTS)
yuvhsync_LDADD = $(LDADD)
am__yuvilace_SOURCES_DIST = yuvilace.c
am_yuvilace_OBJECTS = yuvilace.$(OBJEXT)
yuvilace_OBJECTS = $(am_yuvilace_OBJECTS)
yuvilace_LDADD = $(LDADD)
am_yuvpixelgraph_OBJECTS = yuvpixelgraph.$(OBJEXT) utilyuv.$(OBJEXT)
yuvpixelgraph_OBJECTS = $(am_yuvpixelgraph_OBJECTS)
yuvpixelgraph_LDADD = $(LDADD)
am_yuvrfps_OBJECTS = yuvrfps.$(OBJEXT)
yuvrfps_OBJECTS = $(am_yuvrfps_OBJECTS)
yuvrfps_LDADD = $(LDADD)
am__yuvsubtitle_SOURCES_DIST = yuvsubtitle.c utilyuv.c
am_yuvsubtitle_OBJECTS = yuvsubtitle.$(OBJEXT) \
	utilyuv.$(OBJEXT)
yuvsubtitle_OBJECTS = $(am_yuvsubtitle_OBJECTS)
yuvsubtitle_LDADD = $(LDADD)
am_yuvtbilateral_OBJECTS = yuvtbilateral.$(OBJEXT) utilyuv.$(OBJEXT)
yuvtbilateral_OBJECTS = $(am_yuvtbilateral_OBJECTS)
yuvtbilateral_LDADD = $(LDADD)
am_yuvtshot_OBJECTS = yuvtshot.$(OBJEXT) utilyuv.$(OBJEXT)
yuvtshot_OBJECTS = $(am_yuvtshot_OBJECTS)
yuvtshot_LDADD = $(LDADD)
am_yuvwater_OBJECTS = yuvwater.$(OBJEXT)
yuvwater_OBJECTS = $(am_yuvwater_OBJECTS)
yuvwater_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
OBJCCOMPILE = $(OBJC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_OBJCFLAGS) $(OBJCFLAGS)
OBJCLD = $(OBJC)
OBJCLINK = $(OBJCLD) $(AM_OBJCFLAGS) $(OBJCFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libav_bitrate_SOURCES) $(libav2yuv_SOURCES) \
	$(libavmux_SOURCES) $(yuvCIFilter_SOURCES) \
	$(yuvaddetect_SOURCES) $(yuvadjust_SOURCES) \
	$(yuvaifps_SOURCES) $(yuvbilateral_SOURCES) \
	$(yuvconvolve_SOURCES) $(yuvcrop_SOURCES) \
	$(yuvdeinterlace_SOURCES) $(yuvdiag_SOURCES) \
	$(yuvdiff_SOURCES) $(yuvfade_SOURCES) $(yuvhsync_SOURCES) \
	$(yuvilace_SOURCES) $(yuvpixelgraph_SOURCES) \
	$(yuvrfps_SOURCES) $(yuvsubtitle_SOURCES) \
	$(yuvtbilateral_SOURCES) $(yuvtshot_SOURCES) \
	$(yuvwater_SOURCES)
DIST_SOURCES = $(am__libav_bitrate_SOURCES_DIST) \
	$(am__libav2yuv_SOURCES_DIST) $(am__libavmux_SOURCES_DIST) \
	$(am__yuvCIFilter_SOURCES_DIST) $(yuvaddetect_SOURCES) \
	$(yuvadjust_SOURCES) $(yuvaifps_SOURCES) \
	$(yuvbilateral_SOURCES) $(yuvconvolve_SOURCES) \
	$(yuvcrop_SOURCES) $(yuvdeinterlace_SOURCES) \
	$(am__yuvdiag_SOURCES_DIST) $(yuvdiff_SOURCES) \
	$(yuvfade_SOURCES) $(yuvhsync_SOURCES) \
	$(am__yuvilace_SOURCES_DIST) $(yuvpixelgraph_SOURCES) \
	$(yuvrfps_SOURCES) $(am__yuvsubtitle_SOURCES_DIST) \
	$(yuvtbilateral_SOURCES) $(yuvtshot_SOURCES) \
	$(yuvwater_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/d332027/Developer/mark_yuv/missing --run aclocal-1.11
AMTAR = ${SHELL} /Users/d332027/Developer/mark_yuv/missing --run tar
AUTOCONF = ${SHELL} /Users/d332027/Developer/mark_yuv/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/d332027/Developer/mark_yuv/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/d332027/Developer/mark_yuv/missing --run automake-1.11
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = 
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = 
EXEEXT = 
FFMPEG_CFLAGS = 
FFMPEG_LIBS = 
FFTW_CFLAGS = 
FFTW_LIBS = 
FREETYPE_CFLAGS = 
FREETYPE_LIBS = 
GREP = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/d332027/Developer/mark_yuv/missing --run makeinfo
MJPEG_CFLAGS = 
MJPEG_LIBS = 
MKDIR_P = ./install-sh -c -d
OBJC = 
OBJCDEPMODE = 
OBJCFLAGS = 
OBJCPP = 
OBJEXT = o
PACKAGE = MarkYUV
PACKAGE_BUGREPORT = mjpeg0@silicontrip.org
PACKAGE_NAME = MarkYUV
PACKAGE_STRING = MarkYUV 1.4
PACKAGE_TARNAME = markyuv
PACKAGE_URL = 
PACKAGE_VERSION = 1.4
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.4
abs_builddir = /Users/d332027/Developer/mark_yuv
abs_srcdir = /Users/d332027/Developer/mark_yuv
abs_top_builddir = /Users/d332027/Developer/mark_yuv
abs_top_srcdir = /Users/d332027/Developer/mark_yuv
ac_ct_CC = gcc
ac_ct_OBJC = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/d332027/Developer/mark_yuv/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/./install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
OPT_FLAG = -O3 -ftree-vectorize
AM_LDFLAGS = 
AM_CFLAGS = 
FFMPEG_FLAGS = $(CODECFLAGS) -lswscale -lavcodec -lavformat -lavutil
libav_bitrate_SOURCES = libav-bitrate.c
libav2yuv_SOURCES = libav2yuv.c
libavmux_SOURCES = libavmux.c
FREETYPEFLAGS = -L/usr/X11/lib -lfreetype
yuvsubtitle_SOURCES = yuvsubtitle.c utilyuv.c
yuvdiag_SOURCES = yuvdiag.c
COCOAFLAGS = -framework QuartzCore -framework Foundation -framework AppKit
yuvCIFilter_SOURCES = yuvCIFilter.m
yuvilace_SOURCES = yuvilace.c
yuvaddetect_SOURCES = yuvaddetect.c 
yuvadjust_SOURCES = yuvadjust.c 
yuvaifps_SOURCES = yuvaifps.c
yuvconvolve_SOURCES = yuvconvolve.c
yuvcrop_SOURCES = yuvcrop.c
yuvdeinterlace_SOURCES = yuvdeinterlace.c utilyuv.c
yuvdiff_SOURCES = yuvdiff.c utilyuv.c
yuvfade_SOURCES = yuvfade.c
yuvhsync_SOURCES = yuvhsync.c
yuvrfps_SOURCES = yuvrfps.c
yuvtshot_SOURCES = yuvtshot.c utilyuv.c
yuvwater_SOURCES = yuvwater.c
yuvbilateral_SOURCES = yuvbilateral.c utilyuv.c
yuvtbilateral_SOURCES = yuvtbilateral.c utilyuv.c
yuvpixelgraph_SOURCES = yuvpixelgraph.c utilyuv.c
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .m .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
libav-bitrate$(EXEEXT): $(libav_bitrate_OBJECTS) $(libav_bitrate_DEPENDENCIES) 
	@rm -f libav-bitrate$(EXEEXT)
	$(LINK) $(libav_bitrate_OBJECTS) $(libav_bitrate_LDADD) $(LIBS)
libav2yuv$(EXEEXT): $(libav2yuv_OBJECTS) $(libav2yuv_DEPENDENCIES) 
	@rm -f libav2yuv$(EXEEXT)
	$(LINK) $(libav2yuv_OBJECTS) $(libav2yuv_LDADD) $(LIBS)
libavmux$(EXEEXT): $(libavmux_OBJECTS) $(libavmux_DEPENDENCIES) 
	@rm -f libavmux$(EXEEXT)
	$(LINK) $(libavmux_OBJECTS) $(libavmux_LDADD) $(LIBS)
yuvCIFilter$(EXEEXT): $(yuvCIFilter_OBJECTS) $(yuvCIFilter_DEPENDENCIES) 
	@rm -f yuvCIFilter$(EXEEXT)
	$(OBJCLINK) $(yuvCIFilter_OBJECTS) $(yuvCIFilter_LDADD) $(LIBS)
yuvaddetect$(EXEEXT): $(yuvaddetect_OBJECTS) $(yuvaddetect_DEPENDENCIES) 
	@rm -f yuvaddetect$(EXEEXT)
	$(LINK) $(yuvaddetect_OBJECTS) $(yuvaddetect_LDADD) $(LIBS)
yuvadjust$(EXEEXT): $(yuvadjust_OBJECTS) $(yuvadjust_DEPENDENCIES) 
	@rm -f yuvadjust$(EXEEXT)
	$(LINK) $(yuvadjust_OBJECTS) $(yuvadjust_LDADD) $(LIBS)
yuvaifps$(EXEEXT): $(yuvaifps_OBJECTS) $(yuvaifps_DEPENDENCIES) 
	@rm -f yuvaifps$(EXEEXT)
	$(LINK) $(yuvaifps_OBJECTS) $(yuvaifps_LDADD) $(LIBS)
yuvbilateral$(EXEEXT): $(yuvbilateral_OBJECTS) $(yuvbilateral_DEPENDENCIES) 
	@rm -f yuvbilateral$(EXEEXT)
	$(LINK) $(yuvbilateral_OBJECTS) $(yuvbilateral_LDADD) $(LIBS)
yuvconvolve$(EXEEXT): $(yuvconvolve_OBJECTS) $(yuvconvolve_DEPENDENCIES) 
	@rm -f yuvconvolve$(EXEEXT)
	$(LINK) $(yuvconvolve_OBJECTS) $(yuvconvolve_LDADD) $(LIBS)
yuvcrop$(EXEEXT): $(yuvcrop_OBJECTS) $(yuvcrop_DEPENDENCIES) 
	@rm -f yuvcrop$(EXEEXT)
	$(LINK) $(yuvcrop_OBJECTS) $(yuvcrop_LDADD) $(LIBS)
yuvdeinterlace$(EXEEXT): $(yuvdeinterlace_OBJECTS) $(yuvdeinterlace_DEPENDENCIES) 
	@rm -f yuvdeinterlace$(EXEEXT)
	$(LINK) $(yuvdeinterlace_OBJECTS) $(yuvdeinterlace_LDADD) $(LIBS)
yuvdiag$(EXEEXT): $(yuvdiag_OBJECTS) $(yuvdiag_DEPENDENCIES) 
	@rm -f yuvdiag$(EXEEXT)
	$(LINK) $(yuvdiag_OBJECTS) $(yuvdiag_LDADD) $(LIBS)
yuvdiff$(EXEEXT): $(yuvdiff_OBJECTS) $(yuvdiff_DEPENDENCIES) 
	@rm -f yuvdiff$(EXEEXT)
	$(LINK) $(yuvdiff_OBJECTS) $(yuvdiff_LDADD) $(LIBS)
yuvfade$(EXEEXT): $(yuvfade_OBJECTS) $(yuvfade_DEPENDENCIES) 
	@rm -f yuvfade$(EXEEXT)
	$(LINK) $(yuvfade_OBJECTS) $(yuvfade_LDADD) $(LIBS)
yuvhsync$(EXEEXT): $(yuvhsync_OBJECTS) $(yuvhsync_DEPENDENCIES) 
	@rm -f yuvhsync$(EXEEXT)
	$(LINK) $(yuvhsync_OBJECTS) $(yuvhsync_LDADD) $(LIBS)
yuvilace$(EXEEXT): $(yuvilace_OBJECTS) $(yuvilace_DEPENDENCIES) 
	@rm -f yuvilace$(EXEEXT)
	$(LINK) $(yuvilace_OBJECTS) $(yuvilace_LDADD) $(LIBS)
yuvpixelgraph$(EXEEXT): $(yuvpixelgraph_OBJECTS) $(yuvpixelgraph_DEPENDENCIES) 
	@rm -f yuvpixelgraph$(EXEEXT)
	$(LINK) $(yuvpixelgraph_OBJECTS) $(yuvpixelgraph_LDADD) $(LIBS)
yuvrfps$(EXEEXT): $(yuvrfps_OBJECTS) $(yuvrfps_DEPENDENCIES) 
	@rm -f yuvrfps$(EXEEXT)
	$(LINK) $(yuvrfps_OBJECTS) $(yuvrfps_LDADD) $(LIBS)
yuvsubtitle$(EXEEXT): $(yuvsubtitle_OBJECTS) $(yuvsubtitle_DEPENDENCIES) 
	@rm -f yuvsubtitle$(EXEEXT)
	$(LINK) $(yuvsubtitle_OBJECTS) $(yuvsubtitle_LDADD) $(LIBS)
yuvtbilateral$(EXEEXT): $(yuvtbilateral_OBJECTS) $(yuvtbilateral_DEPENDENCIES) 
	@rm -f yuvtbilateral$(EXEEXT)
	$(LINK) $(yuvtbilateral_OBJECTS) $(yuvtbilateral_LDADD) $(LIBS)
yuvtshot$(EXEEXT): $(yuvtshot_OBJECTS) $(yuvtshot_DEPENDENCIES) 
	@rm -f yuvtshot$(EXEEXT)
	$(LINK) $(yuvtshot_OBJECTS) $(yuvtshot_LDADD) $(LIBS)
yuvwater$(EXEEXT): $(yuvwater_OBJECTS) $(yuvwater_DEPENDENCIES) 
	@rm -f yuvwater$(EXEEXT)
	$(LINK) $(yuvwater_OBJECTS) $(yuvwater_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/libav-bitrate.Po
include ./$(DEPDIR)/libav2yuv.Po
include ./$(DEPDIR)/libavmux.Po
include ./$(DEPDIR)/utilyuv.Po
include ./$(DEPDIR)/yuvCIFilter.Po
include ./$(DEPDIR)/yuvaddetect.Po
include ./$(DEPDIR)/yuvadjust.Po
include ./$(DEPDIR)/yuvaifps.Po
include ./$(DEPDIR)/yuvbilateral.Po
include ./$(DEPDIR)/yuvconvolve.Po
include ./$(DEPDIR)/yuvcrop.Po
include ./$(DEPDIR)/yuvdeinterlace.Po
include ./$(DEPDIR)/yuvdiag.Po
include ./$(DEPDIR)/yuvdiff.Po
include ./$(DEPDIR)/yuvfade.Po
include ./$(DEPDIR)/yuvhsync.Po
include ./$(DEPDIR)/yuvilace.Po
include ./$(DEPDIR)/yuvpixelgraph.Po
include ./$(DEPDIR)/yuvrfps.Po
include ./$(DEPDIR)/yuvsubtitle.Po
include ./$(DEPDIR)/yuvtbilateral.Po
include ./$(DEPDIR)/yuvtshot.Po
include ./$(DEPDIR)/yuvwater.Po

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.m.o:
	$(OBJCCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
	source='$<' object='$@' libtool=no \
	DEPDIR=$(DEPDIR) $(OBJCDEPMODE) $(depcomp) \
	$(OBJCCOMPILE) -c -o $@ $<

.m.obj:
	$(OBJCCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
	source='$<' object='$@' libtool=no \
	DEPDIR=$(DEPDIR) $(OBJCDEPMODE) $(depcomp) \
	$(OBJCCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


libav2yuv: libav2yuv.c utilyuv.o
	gcc $(FFMPEG_FLAGS) $(LDFLAGS) $(CFLAGS) -o libav2yuv utilyuv.o $<

libav-bitrate: libav-bitrate.c utilyuv.o
	gcc $(FFMPEG_FLAGS) $(LDFLAGS) $(CFLAGS) -o libav-bitrate  $<

libavmux: libavmux.c utilyuv.o
	gcc $(FFMPEG_FLAGS) $(LDFLAGS) $(CFLAGS) -o libavmux $<

yuvsubtitle: yuvsubtitle.o utilyuv.o
	gcc $(LDFLAGS) $(CFLAGS) $(FREETYPEFLAGS) -o yuvsubtitle $<

yuvdiag: yuvdiag.o utilyuv.o
	gcc $(LDFLAGS) $(CFLAGS) $(FREETYPEFLAGS) -o yuvdiag utilyuv.o $<

yuvCIFilter: yuvCIFilter.o utilyuv.o
	gcc $(LDFLAGS) $(CFLAGS) $(COCOAFLAGS) -o yuvCIFilter $<

yuvilace: yuvilace.o  utilyuv.o
	gcc $(LDFLAGS) $(CFLAGS) $(FFTWFLAGS) -o yuvilace utilyuv.o $<

.c.o:
	gcc $(AM_CFLAGS) -c -o $@ $<

clean:
	 rm -f *.o $(TARGETS)

install:
	cp $(TARGETS) /usr/local/bin

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
